export const mockUserData = {
  id: "user1",
  name: "John Doe",
  username: "johndoe",
  bio: "Skibi toilet, memelord, and web developer. Lover of all things tech and brainrot.",
  profileImage: "https://placehold.co/150",
  coverImage: "https://placehold.co/800x200/789/fff",
  location: "Gothenburg, Sweden",
  joinDate: "May 2025",
  following: 123,
  followers: 4567,
  likes: ["tweet2", "tweet4"],
};

export const mockTweets = [
  {
    id: "tweet1",
    userId: "user1",
    userName: "John Doe",
    userHandle: "johndoe",
    userImage: "https://placehold.co/150",
    content:
      "Just launched my new website! Check it out at reddit.com #webdev #launch",
    time: "2h",
    likes: 45,
    retweets: 12,
    comments: 8,
    isReply: false,
    hasMedia: false,
  },
  {
    id: "tweet2",
    userId: "user1",
    userName: "John Doe",
    userHandle: "johndoe",
    userImage: "https://placehold.co/150",
    content: "Beautiful sunset today! #nature",
    media: "https://via.placeholder.com/500x300",
    time: "5h",
    likes: 23,
    retweets: 7,
    comments: 2,
    isReply: false,
    hasMedia: true,
  },
  {
    id: "tweet3",
    userId: "user1",
    userName: "John Doe",
    userHandle: "johndoe",
    userImage: "https://via.placeholder.com/150",
    content:
      "Just finished reading 'coding for dummies'. Highly recommend it to anyone looking to build better code!",
    time: "1d",
    likes: 67,
    retweets: 12,
    comments: 8,
    isReply: false,
    hasMedia: false,
  },
  {
    id: "tweet4",
    userId: "user1",
    userName: "John Doe",
    userHandle: "johndoe",
    userImage: "https://via.placeholder.com/150",
    content: "@Yabadabadoooo!",
    time: "2d",
    likes: 12,
    retweets: 2,
    comments: 1,
    isReply: true,
    hasMedia: false,
  },
  {
    id: "tweet5",
    userId: "user2",
    userName: "Jane Smith",
    userHandle: "janesmith",
    userImage: "https://via.placeholder.com/150",
    content: "Beautiful day for hiking! #outdoors #nature",
    media: "https://via.placeholder.com/500x300",
    time: "3d",
    likes: 89,
    retweets: 15,
    comments: 7,
    isReply: false,
    hasMedia: true,
  },
];
