name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies and run tests
        working-directory: ./frontend
        run: |
          npm ci
          npm test

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "6.0"

      - name: Install dependencies and run tests
        working-directory: ./backend
        run: |
          npm ci
          npm test -- --forceExit --detectOpenHandles
        env:
          MONGODB_URI: mongodb://localhost:27017/twitter_test
          JWT_SECRET: test_secret_key_for_github_actions
          PORT: 5001

e2e-tester:
  name: E2E Tests
  runs-on: ubuntu-latest
  needs: [frontend, backend]

  steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: "npm"
        cache-dependency-path: "./e2e-tester/package-lock.json"

    - name: Start backend
      working-directory: ./backend
      run: |
        npm ci
        npm start &
        sleep 5
      env:
        MONGODB_URI: mongodb://localhost:27017/twitter_e2e
        JWT_SECRET: test_secret_key_for_e2e
        PORT: 5001

    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: "6.0"

    - name: Start frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        npm run preview &
        sleep 5

    - name: Install Playwright browsers
      working-directory: ./e2e-tester
      run: |
        npm ci
        npx playwright install --with-deps chromium

    - name: Run Playwright tests
      working-directory: ./e2e-tester
      run: |
        npx playwright test
      env:
        CI: true

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: e2e-tester/playwright-report/
        retention-days: 30
